-- MySQL Script generated by MySQL Workbench
-- Sat 17 Nov 2018 05:38:39 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema msgrdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema msgrdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `msgrdb` ;
USE `msgrdb` ;

-- -----------------------------------------------------
-- Table `msgrdb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msgrdb`.`User` ;

CREATE TABLE IF NOT EXISTS `msgrdb`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `account_created` DATETIME NOT NULL,
  `bio` VARCHAR(5000) NULL,
  PRIMARY KEY (`id`)
);


-- -----------------------------------------------------
-- Table `msgrdb`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msgrdb`.`Message` ;

CREATE TABLE IF NOT EXISTS `msgrdb`.`Message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `poster` INT UNSIGNED NOT NULL,
  `posted_date` DATETIME NOT NULL,
  `message` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `poster`
    FOREIGN KEY (`poster`)
    REFERENCES `msgrdb`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `msgrdb`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msgrdb`.`Comment` ;

CREATE TABLE IF NOT EXISTS `msgrdb`.`Comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `msg_id` INT UNSIGNED NOT NULL,
  `commenter_id` INT UNSIGNED NOT NULL,
  `posted_date` DATETIME NOT NULL,
  `message` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `msg_id`
    FOREIGN KEY (`msg_id`)
    REFERENCES `msgrdb`.`Message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commenter_id`
    FOREIGN KEY (`commenter_id`)
    REFERENCES `msgrdb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `msgrdb`.`Follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msgrdb`.`Follow` ;

CREATE TABLE IF NOT EXISTS `msgrdb`.`Follow` (
  `follower_id` INT UNSIGNED NOT NULL,
  `following_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`follower_id`, `following_id`),
  CONSTRAINT `follower_id`
    FOREIGN KEY (`follower_id`)
    REFERENCES `msgrdb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `following_id`
    FOREIGN KEY (`following_id`)
    REFERENCES `msgrdb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
